# Generated by Django 4.2.7 on 2023-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summa',
            name='descrip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='summa',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
